alerts:
- rule: DEPLOYMENT_FAILED
- rule: DOMAIN_FAILED
domains:
- domain: api.tradinglab.xyz
  type: PRIMARY
name: tradinglab-webback
region: fra
services:
- environment_slug: go
  github:
    branch: main
    deploy_on_push: true
    repo: TradingLabXYZ/WebBack
  http_port: 8080
  instance_count: 1
  instance_size_slug: basic-xxs
  name: tradinglab-webback
  routes:
  - path: /
  run_command: bin/WebBack this_is_a_test
  source_dir: /
