info:
  contact: {}
  description: Interact with TradingLab programmatically
  title: TradingLab API
  version: "1.0"
paths:
  /list_trades:
    get:
      description: Retrive a list containing the codes of each trades available CIAO
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              type: string
            type: array
      summary: Get a list trades' codes
securityDefinitions:
  BearerAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
